version: '3.2'
services:
  census:
    build: .
    volumes:
      - ./census/:/opt/census
      - ./data/:/opt/data
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    ports:
      - "8000:8000"
